export const IMAGE_UPLOAD_PENDING = "IMAGE_UPLOAD_PENDING";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_FAILURE = "IMAGE_UPLOAD_FAILURE";
export const SET_IMAGE_PROGRESS = "SET_IMAGE_PROGRESS";
